### ISSUE TITLE
Test failures on Node 14 for Solid integration tests

### ISSUE THREAD

**Issue by rubensworks** [comunica/comunica#1106]
#### Issue type:

- :bug: Bug 

____
#### Description:

@Laurin-W It looks like builds started failing on Node 14 since your Solid integration tests contribution in https://github.com/comunica/comunica/commit/c6965a74697e0a7616e18c8e362276b30441db3a with error like these:

```
TypeError: cluster._getServer is not a function

       96 |     // Start up the server
       97 |     app = await createApp();
    >  98 |     await app.start();
          |     ^
       99 |
      100 |     // Generate secret
      101 |     secret = await getSecret();
```

Not sure why it didn't fail before though. Maybe it depends on the order of test execution.

Also tagging @jeswr in here.

**Comment by rubensworks** [comment]
_Might_ be related to https://github.com/comunica/comunica/blob/4dd99fee904c64e9ef700eb5080197c4a03a36fa/packages/actor-init-query/test/HttpServiceSparqlEndpoint-test.ts#L55 but not sure.

**Comment by Laurin-W** [comment]
Hey @rubensworks, sorry für the late reply. Will be having a deep dive this weekend :)
